### ISSUE TITLE
Feature: Add Lamar benchmark 

### ISSUE THREAD

**Issue by idealist1508** [danielpalme/IocPerformance#100]
Please add [Lamar](https://github.com/jasperfx/Lamar). Thanks

**Comment by danielpalme** [comment]
Could you create a PR?
Branch already exists: https://github.com/danielpalme/IocPerformance/tree/lamar
But I was not able to get it working the last time I tried.

**Comment by danielpalme** [comment]
Just tried again.
I get strange exceptions when I try to resolve instances provided by the Lamar container.

E.g. `Mirosoft.Build.Framework` or `System.Web.Razor, Version=1.0.0.` is missing.

I have no idea what causes this.

**Comment by idealist1508** [comment]
Some nuget packages are missing. I fix it. See PR

**Comment by danielpalme** [comment]
Thanks! Results have been updated.
