### ISSUE TITLE
Cannot build with 4.7

### ISSUE THREAD

**Issue by JamieMeyer** [danielpalme/IocPerformance#106]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0116	A namespace cannot directly contain members such as fields or methods	IocPerformance	D:\Code\IocPerformance-master\IocPerformance\Adapters\DryIocZero\Container.Generated.cs	1	Active

Building with 4.7.2.

Deleting the contents of this file allowed it to build and execute successfully. Downloaded projects should just "work" out of the box, without the need to understand build errors.

**Comment by danielpalme** [comment]
Just tried it myself. I downloaded the code and was able to compile without issues.
