### ISSUE TITLE
Multithreaded performance is not being measured accurately

### ISSUE THREAD

**Issue by Barsonax** [danielpalme/IocPerformance#110]
Noticed that the current benchmark does not measure the multithreaded performance accurately enough, especially when containers like singularity can do their work in less than 10 nanoseconds. I believe this is because there's too much overhead in the way the benchmark is done currently. Increasing the sample size might lead to more accurate results.

When you do this you will see that for alot of containers the multithreaded results will be faster like they should be.

**Comment by danielpalme** [comment]
Correct, but then the execution of the complete benchmark would take several hours. Not every container is as fast as _singularity_.

**Comment by Barsonax** [comment]
Good point.

A solution could be to execute a variable amount of itterations per adapter. Benchmarkdotnet does something like this by calculating how much itterations fit in a certain time frame.

While calculating that might be a bit complex simply giving a adapter a way to specify how many itterations should be done should work as well.

**Comment by danielpalme** [comment]
If you like you can change that. I won't invest any time in this benchmark any more (apart from updating the containers from time to time).
