### ISSUE TITLE
Add VS-Mef

### ISSUE THREAD

**Issue by znakeeye** [danielpalme/IocPerformance#120]
Should be fairly easy to add?

https://github.com/Microsoft/vs-mef

**Comment by danielpalme** [comment]
Would you like to send a PR?

**Comment by jzabroski** [comment]
Almost seems like GitHub could use a neutral ChatBot to respond to "Hey, I think this is easy to do..." with "Would you like to send a PR (for that easy to add feature)?"

**Comment by Barsonax** [comment]
Why not implement a bot that implements the feature for you then? 😉

**Comment by znakeeye** [comment]
In most bug/feature tracking systems, you first report an issue. The implementation is usually added after a more detailed analysis.

Yes, I would like to send a PR at some point. If I get hit by a car before doing so, it's certainly good to have an issue ID to refer to.

**Comment by BalintPogatsa** [comment]
I've done some tests with VS-Mef.
The only performance indicators which were better than Mef2 (2-3 times faster):
 - Prepare And Register
 - Prepare And Register And Simple Resolve
In every other benchmark Mef2 produced way better result (40 times)

I'm just experimenting with VS-Mef so there is a chance that I've done something in a suboptimal way.

The problem with adding this PR is that VS-Mef doesn't support generics and it's has a build step which fails on ImportGeneric. If I don't use their build step, the only advantage over Mef2 disappears as well.

![image](https://user-images.githubusercontent.com/10234427/62710103-f67d2200-b9f6-11e9-8e2d-fb1b81090ec1.png)

![image](https://user-images.githubusercontent.com/10234427/62710131-04cb3e00-b9f7-11e9-9e78-c67144e2e928.png)

**Comment by weltkante** [comment]
Maybe you can share your implementation instead of just numbers and saying "you aren't sure if you done it right" ?

**Comment by AArnott** [comment]
I'm giving it a go.

**Comment by znakeeye** [comment]
It would also be of interest to see how `vs-mef` performs when loading from a serialized graph. It's certainly faster than standard `MEF`.

@weltkante, I don't think he can share the implementation until the next version of `vs-mef`. Mainly due to [this PR](https://github.com/microsoft/vs-mef/pull/143).

**Comment by AArnott** [comment]
It's true, right now I'm consuming that PR to make this easier, but IMO the API for this perf test should provide generic type arguments so that all libraries work since generic type -> Type is much easier than Type -> generic type.

**Comment by danielpalme** [comment]
I just removed DryIocZero and Cauldron (both are using Fody).
Build should now work faster and reliably.

**Comment by dadhi** [comment]
DryIocZero does not use Fody, but it's fine.

**Comment by danielpalme** [comment]
@dadhi
Sorry, will add it again tomorrow.

**Comment by BalintPogatsa** [comment]
I've also uploaded my sources where I'm using the latest AppHost package: https://github.com/BalintPogatsa/IocPerformance

I've excluded all other adapters besides Mef2 and VS Mef for now, to make the comparison fast.
