### ISSUE TITLE
Add Microsoft.Extensions.Hosting

### ISSUE THREAD

**Issue by andreinitescu** [danielpalme/IocPerformance#122]
First, thank you very much for your work!

Would be very interesting to add [Microsoft.Extensions.Hosting](https://www.nuget.org/packages/Microsoft.Extensions.Hosting) and see the results. 
See https://montemagno.com/add-asp-net-cores-dependency-injection-into-xamarin-apps-with-hostbuilder/

**Comment by danielpalme** [comment]
I guess that's already implemented.
Please have a look at "Microsoft Extensions DependencyInjection 2.2.0" in the [results](https://danielpalme.github.io/IocPerformance/).

**Comment by andreinitescu** [comment]
Thanks! The link points to an old repo so I thought you're testing the old version.
Maybe it would be better to point to NuGet instead? 
https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/
NuGet page has a link to the GitHub repo.

**Comment by andreinitescu** [comment]
I am referring to the link from the results page, it points to "https://github.com/aspnet/DependencyInjection".

**Comment by danielpalme** [comment]
Fixed in cd7b852d3b06a4bb790c2c6c0754adcfaa0d58cb

**Comment by andreinitescu** [comment]
Thank you. I wanted to do a PR for this in case you agreed, but many thanks again
