### ISSUE TITLE
Performance regression in singularity

### ISSUE THREAD

**Issue by Barsonax** [danielpalme/IocPerformance#129]
I have noticed a rather big sudden performance regression for Singularity in this benchmark which I cannot reproduce (by checking out this repo and running the benchmarks) and also iam not aware of any changes made to the code that might have caused this.

Just speculating here but was the benchmark accidentally run in debug mode?

**Comment by danielpalme** [comment]
Benchmark is always executed in _Release_ mode.
I don't know what causes the regression.

I just executed the benchmark again (Release mode, all other applications closed).
This is the result:

![image](https://user-images.githubusercontent.com/859606/64937124-4acabb80-d859-11e9-9d8b-d6081963ba6f.png)

**Comment by Barsonax** [comment]
Strange when I execute this I get different results. Also your results also differ quite alot from the ones in the readme.

**Comment by danielpalme** [comment]
No debugger attached. Same machine as always.

**Comment by Barsonax** [comment]
Strange these results don't make sense. For some reason Singularity is performing way worse in the basic benchmarks but fine in the advanced (the generic one is faster than singleton...).

Have to investigate further what causes this.

**Comment by Barsonax** [comment]
These are the results I get:
![image](https://user-images.githubusercontent.com/19387223/65183842-98674400-da64-11e9-8b50-eaa844712764.png)

Added grace as a comparison since iam running this on a different machine.

**Comment by jzabroski** [comment]
I think you need to go on eBay and buy the following:

Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz
Memory: 15,89GB

Joking, but [joking seriously](https://www.ebay.com/itm/INTEL-NUC6I5SYH-I5-6260U-16GB-DDR4-SODIMM-128GB-SSD/352765849385?epid=10031751117&hash=item52227baf29:g:7IMAAOSwB9Fb4gEe).

**Comment by jzabroski** [comment]
The other option is to ask Daniel to ship you his compiled binaries and then you run the benchmark that way.  Probably a cheaper option to start.

**Comment by Barsonax** [comment]
@jzabroski I think you miss the fact that between runs the variation in the results is also way too high suddenly (even for the same version!)

**Comment by jzabroski** [comment]
I am not sure what variation you are referring to.  When I look at his screenshot and the current readme, they are identical.

**Comment by Barsonax** [comment]
Thats because his screenshot and the current readme are from the same run...

**Comment by Barsonax** [comment]
@danielpalme can you try running only the singularity container benchmark and nothing else? Just to rule out another container's side effect ruining the benchmark?

**Comment by danielpalme** [comment]
I executed the benchmark again. Now Singularity performs much better again.
Maybe some background process on my machine affected the performance.

```
Grace 7.0.0                                  Single      Multi
 Singleton                                       25         46
 Transient                                       34         57
 Combined                                        51         81
 Complex                                         62         76
 Property                                        95        103
 Generics                                        50         77
 IEnumerable                                    288        268
 Conditional                                     40         63
 Child Container                              44819      26587
 Asp Net Core                                   695        603
 Interception With Proxy                        812        496
 Prepare And Register                           140
 Prepare And Register And Simple Resolve        787

Singularity 0.14.0                           Single      Multi
 Singleton                                       24         45
 Transient                                       38         61
 Combined                                        50         88
 Complex                                         65         82
 Property
 Generics                                        49         75
 IEnumerable                                    292        220
 Conditional
 Child Container
 Asp Net Core                                   507        555
 Interception With Proxy
 Prepare And Register                            27
 Prepare And Register And Simple Resolve        443
```

**Comment by Barsonax** [comment]
Jup thats the performance iam used to 👍. Lets keep a eye out for when this happens again (maybe it was caused by a side effect of another container?).
