### ISSUE TITLE
TinyIoC Perfomance

### ISSUE THREAD

**Issue by oscarjaergren** [danielpalme/IocPerformance#137]
This has been brought up in the past, but TinyIOC is one of the largest IOCS out there and should be included in any metrics.

The old issue mentioned VS2017 as the limiting factor, but since we are now on VS2019 and TinyIOC has been updated along with it I feel this warrants being brought up again.

Please add TinyIOC to the comparisons in the future. I believe a lot of people would appreciate this. 
Thanks

**Comment by danielpalme** [comment]
If you like, you can submit a PR.

I will not actively maintain this project any more. Reasons:
- My time is limited
- It's still based on .NET Framework. The benchmark should be rewritten and targeting .NET Core.

**Comment by ENikS** [comment]
@danielpalme  

Would you be willing to allow others to help maintaining this project? Perhaps create a team?

I think it is very useful project for people who is trying to select IoC for their development and could benefit a lot of people and businesses around the world.

**Comment by danielpalme** [comment]
PRs are always welcome.

But as stated in my previous comment the next step would be quite a lot of work.
I would like to rewrite the whole benchmark based on .NET Core with [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet).

I already started the implementation, but due to the lack of time, it's not complete in any way yet.

**Comment by ENikS** [comment]
I am working on Unity 6.x and doing a lot of benchmarks for each step. Why not combine the efforts?

I am sure other IOC authors will contribute as well, if not code, perhaps smart ideas and suggestions. There is a whole IOC council lead by Microsoft that could help.

You can still own and lead the effort if it is important to you...
