### ISSUE TITLE
please make it clear in the description 

### ISSUE THREAD

**Issue by Seabizkit** [danielpalme/IocPerformance#155]
is low better or worse, its not clear

as the graphs contradict the results then

```
Unity 5.11.10
 | 216 148 | 1443 835 | 3326 1995 | 9503 4739
```
```
Microsoft Extensions DependencyInjection 6.0.0 
| 65 57 | 108 82 | 108  109 | 150  115
````
This would indicate that the Microsoft Extensions DependencyInjection is faster yes?

but then in the graphs it shows it like how many instances were created over time

https://danielpalme.github.io/IocPerformance/

So then actually Unity is faster...

**Comment by danielpalme** [comment]
> is low better or worse, its not clear

All measurements represent execution time (how long does the container need to resolve 100.000 instances of a given type).
So lower is better.

> This would indicate that the Microsoft Extensions DependencyInjection is faster yes?

Correct.

> but then in the graphs it shows it like how many instances were created over time

No, the graphs also show the execution time.
The x-axis has a logarithmic scale.

> So then actually Unity is faster...
No, its slower.

![image](https://user-images.githubusercontent.com/859606/208984128-59914a01-1e47-4a79-b572-73e78b632634.png)

**Comment by Seabizkit** [comment]
ok thanks!, its not clear what the y axis is to me then, its should say (time in milliseconds or nano secs) I assumed it was number of operations able to complete in over a period of time.
its just when things are mirco benchmarked this normally like x amount of completions in given time. how many operations you complete in a given time period. like requests per second kind of thing...
But seems kinda* obvious now, but thanks for the excellent explanation.

**Comment by Seabizkit** [comment]
maybe add something which states "low is better"
