### ISSUE TITLE
Skewed `Advanced features`

### ISSUE THREAD

**Issue by asd-and-Rizzo** [danielpalme/IocPerformance#51]
Seems `Prepare And Register` and `Prepare And Register And Simple Resolve` broke `Advanced features` chart. May be  create separate chart for these, this will fix issue and may allow somebody add different initialization routines (e.g. XML, assembly scan or out of previously cached container registrations).

**Comment by danielpalme** [comment]
What do you mean with broken?
It look different, because it contains more results, but it's not wrong.
And if you look at my blog, you will find all charts in the _Downloads_ section:
http://www.palmmedia.de/Blog/2011/8/30/ioc-container-benchmark-performance-comparison

**Comment by asd-and-Rizzo** [comment]
Semantically `Prepare And Register` is not `Advanced`. Plus adding these into `Advanced` really hides perceived  prices for really `Advanced` features. `Advanced` as these where before about runtime jobs of resolving, `Prepare` about start up. Better to judge about these separately for those who not cares about start up time.

**Comment by danielpalme** [comment]
Ok, makes sense to move them to a separate chart.

**Comment by danielpalme** [comment]
Added new chart.
