### ISSUE TITLE
ASP.NET Core Dependency Injection

### ISSUE THREAD

**Issue by amivit** [danielpalme/IocPerformance#62]
https://github.com/aspnet/DependencyInjection

Possible to benchmark this guy too?

**Comment by dotnetjunkie** [comment]
If you take a look at [Daniel's benchmark](http://www.palmmedia.de/Blog/2011/8/30/ioc-container-benchmark-performance-comparison), you'll see it actually lists `Microsoft Framework DependencyInjection`.

**Comment by amivit** [comment]
I just closed my issue a second before you replied. My apologies!
