### ISSUE TITLE
Where is Castle Windsor? 

### ISSUE THREAD

**Issue by ohadschn** [danielpalme/IocPerformance#73]
It is mysteriously missing from the list in the main page:
https://github.com/danielpalme/IocPerformance

Even though a quick search shows some references to it in the code...

**Comment by ipjohnson** [comment]
It was dropped out because castle windsor 3.X is not compatible with castle core 4.0

This [PR](https://github.com/danielpalme/IocPerformance/pull/68) has some comments from one of the castle windsor developers  recommending dropping it from the benchmark till it's compatible with castle core 4.0

**Comment by ohadschn** [comment]
@ipjohnson I see, thanks for explaining.
I take it the 3.X performance was not too great?

**Comment by ipjohnson** [comment]
Faster than some, slower than others ...

Here is the [readme](https://github.com/danielpalme/IocPerformance/blob/8778fe1f68b9edd462b2c6e4c2a2dafc87587f1f/README.md) before the change

**Comment by ohadschn** [comment]
@ipjohnson thanks!
For some reason the graphs don't show it though...

**Comment by ipjohnson** [comment]
@ohadschn  The graphs only show containers that finish in a certain amount of time. Look at the raw numbers listed in the tables it's under Windsor.

**Comment by ohadschn** [comment]
Understood, thanks so much for you patience!
Feel free to close this issue...
