### ISSUE TITLE
tinyioc results?

### ISSUE THREAD

**Issue by bonesoul** [danielpalme/IocPerformance#90]
can't seem to find them?

**Comment by danielpalme** [comment]
TinyIOC is currently ignored. Reason: Not installable in VS 2017

**Comment by sberney** [comment]
What do you mean? I can install TinyIoC in VS2017 and VS2019.

TinyIoC is a pretty heavily used IoC container, it would be nice to see how it compares.

**Comment by jzabroski** [comment]
@sberney The comment you are responding to is literally almost 2 years old.
