### ISSUE TITLE
Use BenchmarkDotNet

### ISSUE THREAD

**Issue by davidfowl** [danielpalme/IocPerformance#98]
Love this benchmark!

Change the custom benchmarking infrastructure to use BDN, it's the de-factor benchmarking tech for .NET projects now and it'll likely produce more accurate results and more detailed measurements (like allocations etc).

/cc @adamsitnik @AndreyAkinshin @mattwarren

**Comment by dadhi** [comment]
Here is decent inheritor BM using the BDN:
https://ipjohnson.github.io/DotNet.DependencyInjectionBenchmarks/

/cc @ipjohnson

**Comment by davidfowl** [comment]
Wow that’s pretty awesome. Also some of these containers are near native speed (same as without a container), I need to see what they do under the covers.

**Comment by danielpalme** [comment]
Duplicate of #77
